#!/usr/bin/env sh

__screenshot_dir="$HOME/pictures/screenshots"

mkdir -p "$__screenshot_dir" || exit 1

__filename="$__screenshot_dir/$(date +'%m-%d-%Y-%H%M%S').png"

grim -g "$(slurp)" - \
    | tee "$__filename" \
    | wl-copy

notify-send -t 3 "Screenshot saved and copied"
