#!/usr/bin/env sh

SCREENSHOT_DIR="$HOME/pictures/screenshots"

mkdir -p "$SCREENSHOT_DIR" || exit 1

FILE="$SCREENSHOT_DIR/$(date +'%m-%d-%Y-%H%M%S').png"

grim -g "$(slurp)" - \
    | tee "$FILE" \
    | wl-copy

notify-send -t 3 "Screenshot saved and copied"
