#!/usr/bin/env sh

__wallpaper_dir="$HOME/pictures/wallpapers/"

mkdir -p "$__wallpaper_dir" || exit 1

__wp_list=$(cd $__wallpaper_dir && find . -type f | cut -c3-)

__wp_select=$(echo "$__wp_list" | rofi -dmenu)

awww img --transition-fps 150 $__wallpaper_dir/$__wp_select
